import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		...builtins
	],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	treeShaking: true,
	outfile: 'main.js',
}).catch(() => process.exit(1));
