/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// main.ts
var add = (a, b) => {
  return a + b;
};
console.log(add(1, 2));
